/**
 * @file    uart_comm.c
 * @brief   Authentication packet TX/RX via USB CDC Virtual COM Port.
 * @details Uses CDC_Transmit_FS() (from usbd_cdc_if.h, generated by CubeMX)
 *          to send the 16-byte auth packet over the Blue Pill's micro USB.
 *          ACK bytes from the Python bridge arrive via CDC_Receive_FS()
 *          callback and are stored in usb_rx_buffer for polling.
 *
 * This file replaces the original USART1/HAL_UART_Transmit implementation.
 * The public API (send_auth_packet, receive_ack, uart_flush_rx) is unchanged —
 * only the transport layer is different.
 *
 * Note on CDC_Transmit_FS return values:
 *   USBD_OK   (0) = packet accepted into USB TX FIFO
 *   USBD_BUSY (2) = USB stack busy with previous packet — retry needed
 *   USBD_FAIL (1) = USB not connected/enumerated
 */

#include "uart_comm.h"
#include "usb_rx_buffer.h"
#include "crc16.h"
#include "main.h"
#include "usbd_cdc_if.h"   /* CDC_Transmit_FS() — generated by CubeMX */
#include <string.h>

/* ========================================================================== */
/*                            PUBLIC API                                      */
/* ========================================================================== */

HAL_StatusTypeDef send_auth_packet(uint16_t score)
{
    AuthPacket pkt;
    uint8_t    retry;
    uint8_t    cdc_result;

    /* --- Build the 16-byte packet --- */

    pkt.device_id[0] = DEVICE_ID_BYTE0;
    pkt.device_id[1] = DEVICE_ID_BYTE1;
    pkt.device_id[2] = DEVICE_ID_BYTE2;
    pkt.device_id[3] = DEVICE_ID_BYTE3;

    pkt.finger_score = score;

    /* Timestamp: ms since boot via HAL_GetTick() */
    pkt.timestamp = (uint64_t)HAL_GetTick();

    /* CRC-16/CCITT over first 14 bytes (payload without CRC field) */
    pkt.crc16 = crc16_ccitt((const uint8_t *)&pkt, AUTH_PAYLOAD_SIZE);

    /* --- Flush stale RX bytes before sending --- */
    uart_flush_rx();

    /* --- Transmit with retry logic --- */
    for (retry = 0; retry < UART_MAX_RETRIES; retry++) {
        /*
         * CDC_Transmit_FS copies data into the USB TX FIFO.
         * Returns USBD_OK immediately — the USB stack handles actual
         * transmission asynchronously. If the USB stack is still busy
         * finishing the previous packet, it returns USBD_BUSY.
         */
        cdc_result = CDC_Transmit_FS((uint8_t *)&pkt, AUTH_PACKET_SIZE);

        if (cdc_result == USBD_OK) {
            /*
             * Give the USB stack a brief moment to actually send the packet
             * before the caller calls receive_ack(). Without this delay,
             * receive_ack() might start polling before the packet leaves.
             */
            HAL_Delay(20);
            return HAL_OK;
        }

        if (cdc_result == USBD_FAIL) {
            /*
             * USB not connected — host hasn't enumerated the CDC device
             * yet, or cable is disconnected.
             */
            return HAL_ERROR;
        }

        /* USBD_BUSY — USB stack still finishing previous TX, wait and retry */
        HAL_Delay(50);
    }

    /* All retries exhausted */
    return HAL_ERROR;
}

uint8_t receive_ack(void)
{
    uint8_t ack_byte = ACK_TIMEOUT;

    /*
     * Poll the USB RX ring buffer. The ring buffer is filled asynchronously
     * by CDC_Receive_FS() in usbd_cdc_if.c (which must call
     * usb_rx_buffer_push() — see hardware guide Step 7).
     */
    if (usb_rx_buffer_pop(&ack_byte, UART_TIMEOUT) == 1U) {
        return ack_byte;
    }

    return ACK_TIMEOUT;
}

void uart_flush_rx(void)
{
    usb_rx_buffer_flush();
}
